### PR TITLE
Fixes issue with Pusher

### PR DESCRIPTION
**Pull request by mlantz**
Corrects channels into array of strings rather than objects

### CODE REVIEW

**Comment by mlantz** [comment]
Provided there are no concerns with this can we get a patch release with this update. Thanks.

**Comment by mpociot** [comment]
Hey can you tell me what was causing this issue?
Because the original master branch doesn't have this fix applied: https://github.com/laravel/framework/blob/7d116dc5a008e69c97f864af79ac46ab6a8d5895/src/Illuminate/Notifications/Events/BroadcastNotificationCreated.php#L57

**Comment by mlantz** [comment]
Not sure why, but the response I was getting back from Pusher was that the channel name was not a string.

Example $channels on PusherBroadcaster without change:

```
array:1 [▼
  0 => PrivateChannel {#579 ▼
    +name: "private-ISOlocity.Repositories.User.User.263"
  }
]
```

with change:

```
array:1 [▼
  0 => "private-ISOlocity.Repositories.User.User.263"
]
```

Result without change:
`
array:2 [▼
  "body" => "Expected channel name to be a string\n"
  "status" => 400
]
`
Result with change:
`array:2 [▼
  "body" => "{}"
  "status" => 200
]`

**Comment by mlantz** [comment]
Looks like in the 5.3 there are a bunch of updates to the PusherBroadcaster such as a new `formatChannels` method which gets the string value from the channels

**Comment by enniel** [comment]
@mlantz In version 5.1 and 5.2, there are no class "Illuminate\Broadcasting\PrivateChannel". See #9, #10 and [PrivateChannel](https://github.com/illuminate/broadcasting/blob/5.1/PrivateChannel.php).

**Comment by mlantz** [comment]
Yeah it seems like the 'backport' of the notifications is rather limited. I updated my app to Laravel 5.3 rather than try to figure this out. Only took like 4 hours, and it was a pretty big and complicated app.

**Pull request closed without merging**
