### PR TITLE
Fix bug with broadcasting system

### PR DESCRIPTION
**Pull request by enniel**
This commit fixed issue #9.

### CODE REVIEW

**Comment by mpociot** [comment]
Thank you for the PR. Would you also be open to adding the broadcasting backport system to our Github organization?
I would create a new repository for you and add you as an administrator.

**Comment by enniel** [comment]
@mpociot Yes, of course.

**Comment by mpociot** [comment]
@enniel I thought about this a bit more. What exactly backports your package?
Because the simplest solution would be to just remove the `PrivateChannel` class from this line: https://github.com/laravel-notification-channels/backport/blob/81ddef9b3fbe383f14d3ac4836eb622e14f58b83/src/Notifications/Events/BroadcastNotificationCreated.php#L57

Then we don't need an extra composer dependency and everything would work as expected.

**Comment by enniel** [comment]
It will not work as expected, because broadcastOn will not give the instance PrivateChannel.

**Comment by osteel** [comment]
Hey guys,

Any progress on this? Facing that same issue now (as #9 )

Cheers

Yannick

**Pull request closed without merging**
